### ISSUE TITLE
Plugin seems broken in 1.20.6

### ISSUE THREAD

**Issue by Myterian** [timbru31/PickupArrows#127]
## What steps will reproduce the problem?
Download and move .jar into plugin folder. Start server.

## Expected output
Picking up arrows.

## What do you see instead?
Can't pick up arrows. Server throws error.

## Log file of the issue/error
[latest.log](https://github.com/user-attachments/files/15519085/latest.log)

## /version output?
This server is running CraftBukkit version 4149-Spigot-e2c1eee-4e7d749 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

## PickupArrows version
6.2.4

## Please provide any additional information below.
Only other plugin in this server is No Ender Grief v. 1.0.1, but it has no impact on the usabilty, as PickupArrows show the same behaviour without any other plugin installed

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid PickupArrows version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks, I'll take a look!

**Comment by timbru31** [comment]
@Myterian can you test https://ci.dustplanet.de/job/PickupArrows/169/artifact/target/PickupArrows.jar please?

**Comment by Myterian** [comment]
looks good 👍

**Comment by timbru31** [comment]
Thanks! I'll release an update in the coming days

**Comment by Myterian** [comment]
Awesome, thank you
