### ISSUE TITLE
Downgrade ?

### ISSUE THREAD

**Issue by ErythroCraft** [timbru31/PickupArrows#130]
# Feature Request

Need 1.20.1

## Please provide any additional information below.

Can you downgrade your version into 1.20.1, please?

THX

[Pastebin](https://pastebin.com/FFdN3sLy)

**Comment by timbru31** [comment]
Just continue to use https://dev.bukkit.org/projects/pickuparrows/files/3164265

**Comment by ErythroCraft** [comment]
@timbru31 it's ok I fixed it by myself
