### ISSUE TITLE
Found a worldguard issue using latest to date dev build of arrow pickup

### ISSUE THREAD

**Issue by axemwa** [timbru31/PickupArrows#28]
## What steps will reproduce the problem?
Citizens NPC's are shooting Phantoms at close range and I think the NPC is attempting to pick up the arrows even though arrow pick up is ignored in my specified world region
## Expected output
No errors in console
## What do you see instead?
Errors in console
## Log file/Console output of the issue/error
https://pastebin.com/sDHFgS9u
## /version output?
[14:15:46 INFO]: This server is running Paper version git-Paper-469 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

## PickupArrows version
Dev Build 202
https://ci.dustplanet.de/job/PickupArrows/202/

## Please provide any additional information below.
[Config.yml](https://pastebin.com/S90vs4w0)
Latest [WorldGuard](http://builds.enginehub.org/job/worldguard?branch=master) & [WorldEdit](http://builds.enginehub.org/job/worldedit?branch=master) Builds
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid PickupArrows version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by axemwa** [comment]
I also suggest adding citizens to the "pickupFrom:" section of the config
eg:

# For help please refer to the bukkit dev page: https://dev.bukkit.org/projects/pickuparrows
usePermissions: false
pickupFrom:
  skeleton:
    fire: true
    normal: true
    spectral: true
    tipped: true
  player:
    fire: true
    normal: true
    spectral: true
    tipped: true
  **citizensnpc:**
    **fire: true
    normal: true
    spectral: true
    tipped: true**
  dispenser:
    fire: true
    normal: true
    spectral: true
    tipped: true
  unknown:
    fire: false
    normal: false
    spectral: false
    tipped: false

**Comment by timbru31** [comment]
The latest version of WorldGuard is v7, isn't it? I remember that they have changed the API.

**Comment by axemwa** [comment]
Yes latest WG 7 in links above

**Comment by axemwa** [comment]
Thanx that fixed it :)
