### ISSUE TITLE
ProjectileHitEvent

### ISSUE THREAD

**Issue by TakoidGit** [timbru31/PickupArrows#48]
## What steps will reproduce the problem?
Unknown.

## Log file of the issue/error
https://pastebin.com/K7u9vMCV

## /version output?

This server is running CraftBukkit version git-Spigot-01d0f04-b7fea42 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

## PickupArrows version

6.20

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid PickupArrows version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks for the report!
Can you share some information how you produced this error (if possible)

**Comment by TakoidGit** [comment]
Players were shooting mobs under water from what I could tell.

**Comment by timbru31** [comment]
This has been fixed with release v6.2.1 - should be soon on BukkitDev or grab it from here: https://ci.dustplanet.de/job/PickupArrows/259/
