### ISSUE TITLE
Add an ingame toggle for picking up arrows

### ISSUE THREAD

**Issue by DrkMatr1984** [timbru31/PickupArrows#5]
Not an issue, but can you maybe add a toggle in game for the player to be able to pick up arrows? Some players may not want to pick up arrows all of the time. Thanks!

**Comment by timbru31** [comment]
Thanks for getting back to late.
Isn't this enhancement achievable via the pickup permission?

**Comment by DrkMatr1984** [comment]
I guess I could add a command that adds the pickup permission and takes it away. *shrugs* Just thought a direct command in game would be better because permissions systems sometimes don't update instantly. (PEX sometimes bugs a bit if you run /pex update too much)

**Comment by timbru31** [comment]
Sounds like a valid reason. Will add the feature in a future version

**Comment by timbru31** [comment]
It's finally live: https://github.com/timbru31/SilkSpawnersEcoAddon

**Comment by DrkMatr1984** [comment]
:O will go ahead and download!  Thanks!

**Comment by timbru31** [comment]
Thanks, really appreciated! ❤️
