### ISSUE TITLE
Crossbows with multishot can duplicate arrows

### ISSUE THREAD

**Issue by OPGuyK** [timbru31/PickupArrows#50]
## What steps will reproduce the problem?
1. Make sure crossbow: normal: true in config.yml
2. Enchant a crossbow with multishot
3. Shoot one arrow with the crossbow

## Expected output
Vanilla behaviour: two side arrows from multishot cannot be collected after shooting
## What do you see instead?
You get all 3 arrows that are shot back, therefore duplicating the original arrow
## Log file of the issue/error
N/A
## /version output?
This server is running Paper version git-Paper-107 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Previous version: git-Paper-85 (MC: 1.14.2)
You are running the latest version

## PickupArrows version
v6.2.1

## Please provide any additional information below.
Video of how to perform this https://www.youtube.com/watch?v=7S8zJOLMqSA
Config.yml
 https://pastebin.com/74Yv9rns
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid PickupArrows version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks for the report, I'll take a look!
